### ISSUE TITLE
Could not find network emulation

### ISSUE THREAD

**Issue by Lectem** [TracerBench/tracerbench#190]
When trying to use tracerbench profile with the `--network` option I'm getting the following error:
 (after calling `tracerbench record-har --url=https://www.tracerbench.com --headless`)
> tracerbench profile ./tracerbench.har --network=3g
>   √ Reading cookies json
>   √ Preparing results folder
>   √ Validating & Cloning HAR file
>   × Recording the live trace
>     → Error: Live Trace could not be captured. Error: Could not find network emulation "[object Object]"
>     Setting trace events
>  »   Error: Error: Error: Live Trace could not be captured. Error: Could not find network emulation "[object Object]"

Sometimes it keeps spinning. I find it a bit weird since I think `conditions.network` should probably be just a string so that the lookup at https://github.com/TracerBench/tracerbench/blob/d3d53204ea4c9fb6bb56896ba4a59a313fa8d5e1/packages/core/src/trace/utils.ts#L178 works ?

**Comment by lynchbomb** [comment]
Thank you for bringing this to our attention. This should be resolved within https://github.com/TracerBench/tracerbench/commit/670308ab784dd0c03029c55c269f8614d62a0464 and available on the next patch release.
