### ISSUE TITLE
unhashed phase name can lead to invalid report output

### ISSUE THREAD

**Issue by makepanic** [TracerBench/tracerbench#237]
Hi,

I noted that marker labels are directly used int the generated javascript.

https://github.com/TracerBench/tracerbench/blob/a5028d7a1627356ab66215f3cdbefaeb9a820ee0/packages/cli/src/static/phase-chart-js-partial.hbs#L2

This means a label containing dots or other characters will generate a broken report page.
E.g. a label `random.words` will generate the following javascript:

```js
 const canvasForrandom.words = document.getElementById('random.words-chart').getContext('2d');
```

It seems like the value used is intended to be something hash like (https://github.com/TracerBench/tracerbench/blob/90b4662eae95eca77c6bfa1c85c5d9b04042c924/packages/cli/src/helpers/create-consumable-html.ts#L257)

Would you be Ok if I open a PR that hashes the label to generate a id? 
For example:

```js
identifierHash = `id${md5sum(label)}`
```

Alternatively one could also normalize the label when setting it as identifierHash or create a new helper that does the normalization.

**Comment by lynchbomb** [comment]
Yeah totally. Sounds good to me! Let me know if you need any help in the process.
