### ISSUE TITLE
CLI documentation improvements

### ISSUE THREAD

**Issue by mike-north** [TracerBench/tracerbench#30]
CLI docs look like they're coming along!

Let's make sure that, as the primary documentation for this tool, the first reviewable draft includes

- [x] CLI output (files, data that can be piped to other commands, etc...) should be described in terms of format and contents - _mainly we need trace.json schema documented somewhere_
- [x] Installation/setup instructions, including any dependencies
- [x] What this tool does, and why I should care - _will be present in top-level documentation_
- [x] Tips for using the tool successfully (i.e, minimizing noise on the machine that's being used to measure)

**Comment by lynchbomb** [comment]
>  What this tool does, and why I should care
> Tips for using the tool successfully (i.e, minimizing noise on the machine that's being used to measure)
> Installation/setup instructions, including any dependencies

These will be part of the user-story and flow docs which will live here:
https://github.com/TracerBench/tracerbench/blob/master/README.md

**Comment by lynchbomb** [comment]
> "should be described in terms of format and contents"

Not sure I follow. Could you provide an example of what you're looking for?

**Comment by lynchbomb** [comment]
> What this tool does, and why I should care - will be present in top-level documentation
> Tips for using the tool successfully (i.e, minimizing noise on the machine that's being used to measure)

These two will be available at the root TracerBench repo. Targeting having docs done EOW this week. 
(https://github.com/TracerBench/tracerbench/blob/master/README.md) <<<< here
