### ISSUE TITLE
Issue tracing with Chrome 90

### ISSUE THREAD

**Issue by lynchbomb** [TracerBench/tracerbench#303]
The latest build of TracerBench is failing benchmarking against Chrome 90. The failure is coming from `core` tracing; with:
`Error: Could not find mark "navigationStart" in trace`.

The team is currently investigating this issue as primary.

**Comment by lifeart** [comment]
With new chrome I see `Could not find Paint event in trace after last mark "domComplete"` time-after-time

**Comment by NullVoxPopuli** [comment]
I'm currently getting:
```
# Fatal error in , line 0
# Check failed: concurrent_marking_handle_ implies !concurrent_marking_handle_->IsValid().
#
#
#
#FailureMessage Object: 0x16f454f98
----- Native stack trace -----

 1: 0x100aeff08 node::NodePlatform::GetStackTracePrinter()::$_3::__invoke() [<nodePath>/node/22.9.0/bin/node]
 2: 0x101e7f78c V8_Fatal(char const*, ...) [<nodePath>/node/22.9.0/bin/node]
 3: 0x10157c7fc cppgc::internal::ConcurrentMarkerBase::~ConcurrentMarkerBase() [<nodePath>/node/22.9.0/bin/node]
```

**Comment by runspired** [comment]
I bumped from v7 to v8 and this issue seems to be back
