### ISSUE TITLE
Generating a HAR file

### ISSUE THREAD

**Issue by skaterdav85** [TracerBench/tracerbench#90]
I am creating a HAR file with `tracerbench create-archive --url https://www.google.com/`, but I noticed that the HAR file doesn't have as much information as when I download a HAR file manually from a browser. Is there a way to get more info using `tracerbench create-archive`?

**Comment by lynchbomb** [comment]
In the latest major release create-archive has been replaced by record-har command which records significantly more data. Please note we now are requiring a cookies file. If your SPA doesn’t require auth simply pass a cookies.json with an empty hash.

**Comment by skaterdav85** [comment]
thanks!
