### ISSUE TITLE
Errors with "tracerbench trace"

### ISSUE THREAD

**Issue by skaterdav85** [TracerBench/tracerbench#91]
Currently I'm running version 3.0.1. I ran the following:

```console
tracerbench trace --url http://localhost:4200/?tracerbench=true --harpath=bin/relationship-performance-tracking/src/trace.har --cookiespath tracerbench-cookies.json --insights
```

and I get this error:

![ember-data_—_-bash_—_172×25](https://user-images.githubusercontent.com/687449/68524080-f2bb9e80-0276-11ea-9f96-a9883070d485.png)

Is there something I am missing?

**Comment by efx** [comment]
@skaterdav85 any chance you could comment with the `tracerbench record-har` command too?

I'm assuming this was part of the work for https://github.com/emberjs/data/pull/6631.

**Comment by efx** [comment]
I ran the following and it worked:
```
tracerbench record-har --url http://localhost:5000 --cookiespath scripts/perf/cookies.json
```
Where `cookies.json` is the snippet from #97.

**Comment by skaterdav85** [comment]
Glad it worked! I've lost context around this since it has been a few months since I last looked at it, so I can't comment on this.

**Comment by lynchbomb** [comment]
I've confirmed this is working with the latest release of Chrome. Closing this.
