### ISSUE TITLE
Latest chrome canary causes throws error

### ISSUE THREAD

**Issue by runspired** [TracerBench/tracerbench#92]
`could not find matching B phase for E phase event` coming from https://github.com/TracerBench/tracerbench/blob/de8e62347b85c2ae0ba8fb3298c008b989cc87c0/packages/tracerbench/src/trace/trace.ts#L257

is thrown when using the runner with chrome canary but not stable:

canary: Version 80.0.3964.0 (Official Build) canary (64-bit)
stable: Version 78.0.3904.97 (Official Build) (64-bit)

**Comment by lynchbomb** [comment]
At the very least as a feature-add lets have the `compare` command include the version of chrome leveraged within the results

**Comment by lynchbomb** [comment]
https://github.com/TracerBench/tracerbench/pull/94

**Comment by runspired** [comment]
I'm seeing something maybe related on chrome 79 where tracerbench can't find Paint events.

Similar to #94 can we output what version the runner is using while the test is in progress? This is useful when we don't get a report since we can't complete a run.
