### ISSUE TITLE
consider adding a contributor's guide

### ISSUE THREAD

**Issue by efx** [TracerBench/tracerbench#99]
As a third-party developer I would benefit from reading and adhering to a contributor's guide. I find they help synchronize expectations.

**Comment by lynchbomb** [comment]
Agreed. Thanks for calling this out. Will get this prioritized.

**Comment by lynchbomb** [comment]
I've included a contributors and guide for RFC here:

https://github.com/TracerBench/tracerbench/blob/master/CONTRIBUTING.md
https://github.com/TracerBench/rfcs
